
twitter_exclude_terms:
  - poop
  - sex
  - drug
  - fuck
  - cunt

facebook_exclude_terms:
  - poop
  - sex
  - drug
  - fuck
  - cunt
  - burnt

twitter_exclude_heroes:
  - codingandrey
  - aestasit
  - eduardsi
  - crazyjooe
  - cvbk
  - ilahah
  - jovchem
